remote: true

experienceLevel:
 internship: false
 entry: true
 associate: true 
 mid-senior level: false  
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: true
 part-time: true
 temporary: false 
 internship: false
 other: false
 volunteer: false

date:
 all time: false
 month: false
 week: false
 24 hours: false

positions:
  - Receptionist

locations:
  - USA

distance: 100

companyBlacklist:


titleBlacklist:
